language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install tox-travis
  - pip install coverage
script:
  - tox

jobs:
  include:
    - stage: coverage
      python: "3.7"
      script:
      - coverage xml
      - curl https://deepsource.io/cli | sh
      - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
