#!/usr/bin/env bash

# This combination of modules worked as of:
#     July 7 2015
# You may need to adjust these as systems change.

module load python
module load cray-netcdf
module load netcdf4-python
module load nco
module load ncl

module list
