#!/usr/bin/env bash

# This combination of modules worked as of:
#     June 5 2016
# You may need to adjust these as systems change.

module unload PrgEnv-pgi PrgEnv-gnu
module load PrgEnv-gnu

module load cray-netcdf-hdf5parallel
module load gcc
module load anaconda-cli106/titan

export PYTHONPATH=''

# activate LIVVkit environment
source activate LIVVkit

module list

