
"""
This is a template validation test that can be used by developers to create new 
validation tests.
"""
import os
import numpy as np
from netCDF4 import Dataset

import livvkit
from livvkit.util import functions
from livvkit.util.functions import Optional
from livvkit.util import elements

def run(name, config):
    """
    Runs the analysis.

    Args:
        name: The name of the test
        config: A dictionary representation of the configuration file

    Returns:
       The result of elements.page with the list of elements to display 
    """
    # TODO: Put your analysis here
    element_list = elements.error("Unimplemented test", "This test contains no analysis code!")
    return elements.page(name, config['description'], element_list)


@Optional
def print_summary():
    """
    Print out a summary generated by this module's summarize_result method
    """
    raise NotImplementedError


@Optional
def summarize_result():
    """
    Provides a snapshot of the results of the analysis to be provided 
    to the sumamry as well as being printed out in this module's 
    print_summary method
    """
    raise NotImplementedError


@Optional
def populate_metadata():
    """
    Generates the metadata responsible for telling the summary what
    is done by this module's run method
    """
    raise NotImplementedError

